/*
 * To change this license header, choose License ;Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ciudadesController;
import controlador.tiquetesController;
import controlador.vuelosController;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import org.json.simple.JSONObject;

/**
 *
 * @author Laura Traslaviña
 */
public class frmCompra extends javax.swing.JFrame {

    /**
     * Creates new form frmCompra
     */
    public JSONObject ciudades = new JSONObject();
    public String refe1, refe2, refe3;
    
    public frmCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCiudadLlegada = new javax.swing.JComboBox<>();
        label4 = new java.awt.Label();
        cmbCiudadSalida = new javax.swing.JComboBox<>();
        label5 = new java.awt.Label();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableVuelos = new javax.swing.JTable();
        btnTiquetes = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        cmbCiudadLlegada.setMaximumRowCount(10);
        cmbCiudadLlegada.setPreferredSize(new java.awt.Dimension(80, 25));
        cmbCiudadLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCiudadLlegadaActionPerformed(evt);
            }
        });

        label4.setText("Ciudad de salida");

        cmbCiudadSalida.setMaximumRowCount(10);
        cmbCiudadSalida.setPreferredSize(new java.awt.Dimension(80, 25));

        label5.setText("Ciudad de llegada");

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tableVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ){public boolean isCellEditable(int row, int column){return false;}});
        jScrollPane2.setViewportView(tableVuelos);

        btnTiquetes.setLabel("Tiquetes");
        btnTiquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiquetesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(btnTiquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbCiudadLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCiudadSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCiudadSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(1, 1, 1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbCiudadLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnTiquetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCiudadLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCiudadLlegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCiudadLlegadaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
     
        String ciud01 = (String) this.cmbCiudadSalida.getSelectedItem();
        String ciud02 = (String) this.cmbCiudadLlegada.getSelectedItem();
        this.ciudades.keySet().forEach(keyStr -> {
            Object keyvalue = this.ciudades.get(keyStr);
            if(ciud01.equals(keyStr)) this.refe1 = (String) keyvalue;            
            if(ciud02.equals(keyStr)) this.refe2 = (String) keyvalue;
        });

        vuelosController ictrl = new vuelosController();
        ResultSet rs = ictrl.consultarVuelos(Integer.parseInt(this.refe1), Integer.parseInt(this.refe2));

                        //Removemos todas lafilas del JTable
        DefaultTableModel model = (DefaultTableModel) this.tableVuelos.getModel();                
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }

        try {
            if(rs.next()){
                this.btnTiquetes.setEnabled(true);
                //Adicionamos los resultados de la consulta de vuelos
                do {
                    String numero = rs.getString("NUMERO");
                    String fecha = rs.getString("FECHA");
                    String hora = rs.getString("HORA");
                    model.addRow(new Object[]{numero, fecha, hora});
                } while (rs.next());
                this.tableVuelos.setRowSelectionInterval(0, 0);

            } else {
              this.btnTiquetes.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmVuelo.class.getName()).log(Level.SEVERE, null, ex);           
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        this.setTitle("Consulta de tiquetes");
        if (this.tableVuelos.getColumnCount() > 0) {
            TableColumn colToDelete = this.tableVuelos.getColumnModel().getColumn(this.tableVuelos.getColumnCount() - 1);
            this.tableVuelos.removeColumn(colToDelete);
            this.tableVuelos.validate();
        }
        
        JTableHeader th = this.tableVuelos.getTableHeader();
        Font fuente = new Font("Verdana", Font.BOLD, 14);
        th.setFont(fuente);
       
        TableColumn col = th.getColumnModel().getColumn(0);
        col.setHeaderValue("Vuelo");
        col = th.getColumnModel().getColumn(1);
        col.setHeaderValue("Fecha");
        col = th.getColumnModel().getColumn(2);
        col.setHeaderValue("Hora");

        ciudadesController ctrC = new ciudadesController();
        ResultSet rs = ctrC.listarCiudades();

        try {
            //llenamos los combobox con las ciuades en las que opera la aerolínea
            while(rs.next()) {
                String ciudad = rs.getString("NOMBRE");
                String refer = rs.getString("REFER");
                this.cmbCiudadSalida.addItem(ciudad);
                this.cmbCiudadLlegada.addItem(ciudad);
                this.ciudades.put(ciudad, refer);
            }

        } catch (SQLException ex) {
            Logger.getLogger(frmVuelo.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnTiquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiquetesActionPerformed
       

        DefaultTableModel model = (DefaultTableModel) this.tableVuelos.getModel();
        Integer row = this.tableVuelos.getSelectedRow();
        if (row != -1) {
            String numvuelo = (String) model.getValueAt(row, 0);            
            tiquetesController ictrl = new tiquetesController();
            ResultSet rs = ictrl.consultarTiquetes(numvuelo);
            frmTiquetes frmT = new frmTiquetes();                
            frmT.setLocationRelativeTo(null);
            frmT.setVisible(true);
            frmT.rs = rs;
            frmT.refe2 = this.refe3;
        } else {
            System.out.println("Seleccione un renglon primero");
        }       
    }//GEN-LAST:event_btnTiquetesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public java.awt.Button btnTiquetes;
    public javax.swing.JComboBox<String> cmbCiudadLlegada;
    public javax.swing.JComboBox<String> cmbCiudadSalida;
    private javax.swing.JScrollPane jScrollPane2;
    public java.awt.Label label4;
    public java.awt.Label label5;
    private javax.swing.JTable tableVuelos;
    // End of variables declaration//GEN-END:variables
}
