/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.tiquetesController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import org.json.simple.JSONObject;

/**
 *
 * @author Laura Traslaviña
 */
public class frmTiquetes extends javax.swing.JFrame {

    /**
     * Creates new form frmTiquetes
     */
    public ResultSet rs = null;
    public String refe2;
    JSONObject tiquetes = new JSONObject();
    
    public frmTiquetes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtPuestos = new javax.swing.JTable();
        btnComprar = new javax.swing.JButton();
        txtTiquete = new java.awt.TextField();
        label1 = new java.awt.Label();
        txtRefer = new java.awt.TextField();
        label2 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtPuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(txtPuestos);

        btnComprar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        txtRefer.setEnabled(false);
        txtRefer.setVisible(false);

        label2.setEnabled(false);
        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Puesto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(txtTiquete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRefer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtTiquete, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnComprar)
                            .addComponent(txtRefer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        label1.getAccessibleContext().setAccessibleName("Referencia de compra");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        try {
            if(this.rs.next()) {
                this.label1.setText(" ");
                this.setTitle("Compra de tiquetes");
                JTableHeader th = this.txtPuestos.getTableHeader();
                TableColumn col = th.getColumnModel().getColumn(0);
                col.setHeaderValue("A");
                col = th.getColumnModel().getColumn(1);
                col.setHeaderValue("B");
                col = th.getColumnModel().getColumn(2);
                col.setHeaderValue("C");
                col = th.getColumnModel().getColumn(3);
                col.setHeaderValue("D");

                DefaultTableModel model = (DefaultTableModel) this.txtPuestos.getModel();                
                int rowCount = model.getRowCount();
                for (int i = rowCount - 1; i >= 0; i--) {
                    model.removeRow(i);
                }

                String fa = "";
                String fb = "";
                String fc = "";
                String fd = "";  
                Integer i = 1;
                do {
                    String dato = this.rs.getString("DATO");
                    this.tiquetes.put(dato, this.rs.getString("REFER"));
                    switch (i) {
                        case 1:
                            fa = dato;
                            break;
                        case 2:
                            fb = dato;
                            break;
                        case 3:
                            fc = dato;
                            break;
                        case 4:
                            fd = dato;
                            break;
                    }
                    if(i == 4) {
                        i = 1;
                        model.addRow(new Object[]{fa, fb, fc, fd});
                    } else {
                        i++;
                    }
                } while (rs.next());
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmVuelo.class.getName()).log(Level.SEVERE, null, ex);           
        }

    }//GEN-LAST:event_formWindowOpened

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
      
        String tiquete = this.txtTiquete.getText();
        this.tiquetes.keySet().forEach(keyStr -> {
            Object keyvalue = this.tiquetes.get(keyStr);
            if(tiquete.equals(keyStr)) this.txtRefer.setText((String) keyvalue);
        });
         
        tiquetesController ictr = new tiquetesController();
        boolean act = ictr.comprarTiquete(this.txtRefer.getText(), this.refe2);
        if(act) {
            this.label1.setText("Referencia de compra " + this.txtRefer.getText());
        }
    }//GEN-LAST:event_btnComprarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnComprar;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    public javax.swing.JTable txtPuestos;
    private java.awt.TextField txtRefer;
    private java.awt.TextField txtTiquete;
    // End of variables declaration//GEN-END:variables
}
